plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
	id 'maven-publish'
	id 'gradle-build-utils' version '1.7.0'
    id 'io.freefair.lombok' version '8.11'
}

Properties props = buildUtils.loadProperties('publish.properties')  // will be empty, if the file is missing

version = "${project.mod_version}+${project.minecraft_version}"
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

int javaVersion = Integer.parseInt(project.java_version)

repositories {
    maven {
        url "https://repo.lclpnet.work/repository/internal"
    }

    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
}

loom {
    splitEnvironmentSourceSets()

    mods {
        "modid" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }

    runs {
        remove client
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    modImplementation "work.lclpnet.mods.kibu:kibu:${project.kibu_version}"
    modImplementation("work.lclpnet.mods.gaco:gaco:${project.gaco_version}")

    include(implementation('com.electronwill.night-config:core:3.8.1'))
    include(implementation('com.electronwill.night-config:toml:3.8.1'))
    include(implementation('org.json:json:20250107'))

    // discord bot
    include(implementation("net.dv8tion:JDA:$project.jda_version") {
        exclude module: 'opus-java' // required for encoding audio into opus, not needed if audio is already provided in opus encoding
        exclude module: 'tink' // required for encrypting and decrypting audio
    })
    include(implementation("com.squareup.okhttp3:okhttp-jvm:5.3.0"))
    include(implementation("com.neovisionaries:nv-websocket-client:2.14"))
    include(implementation("net.sf.trove4j:core:3.1.0"))
    include(implementation("com.squareup.okio:okio:3.16.2"))
    include(implementation("org.apache.commons:commons-collections4:4.5.0"))

    testImplementation "net.fabricmc:fabric-loader-junit:${project.loader_version}"
}

test {
    useJUnitPlatform()
}

processResources {
	inputs.property "version", project.version
    inputs.property "loader_version", project.loader_version
    inputs.property "minecraft_compat", project.minecraft_compat
    inputs.property "java_version", project.java_version

	filesMatching("fabric.mod.json") {
		expand "version": project.version,
                "loader_version": project.loader_version,
                "minecraft_compat": project.minecraft_compat,
                "java_version": project.java_version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release.set(javaVersion)
}

java {
    // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
    withSourcesJar()

    sourceCompatibility = JavaVersion.toVersion(javaVersion)
    targetCompatibility = JavaVersion.toVersion(javaVersion)
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.base.archivesName.get()}"}
	}
}

// configure the maven publication
publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = project.base.archivesName.get()

            from components.java

            pom {
                name = 'player-switch'
                description = 'A Fabric mod for Minecraft: Java Edition that switches the active player after set time intervals. Only one player can play the game at a time '
            }
        }
    }

    // automatically use DEPLOY_URL, DEPLOY_USER and DEPLOY_PASSWORD environment variables
    // or mavenHost, mavenUser and mavenPassword from props
    buildUtils.setupPublishRepository(repositories, props)
}