services:
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: player-switch
    ports:
      - "25565:25565"
    environment:
      - EULA=true
    volumes:
      - ./run:/data

  reset:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: player-switch
    command: ./reset.sh

    volumes:
      - ./run:/data
