services:
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: player-switch
    ports:
      - "25565:25565"
    environment:
      - EULA=true
    user: 1000:1000
    volumes:
      - ./run/config:/app/config
      - ./run/world:/app/world

  reset:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: player-switch
    command: ./reset.sh
    user: 1000:1000

    volumes:
      - ./run/config:/app/config
      - ./run/world:/app/world
