name = "player-switch"
author = "LCLP"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1bdd151bd8c15922781a7bd105d5f5a2c5b1c087c7d41b791489eff6918781db"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"
