name = "player-switch"
author = "LCLP"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98471e02a299f670b1e5160db4addec2cd34b6af3ed421155b28eafeafb96292"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"
