name = "player-switch"
author = "LCLP"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e23e0f3a376df38821737b77b73f0df0b7e95d27f5c8fb19c827caf3af3b6cc"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"
