name: docker-image.yml

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Normalize repository name
        id: repo_name
        run: |
          echo "repo=${REPO,,}" >> $GITHUB_OUTPUT
        env:
          REPO: '${{ github.repository }}'

      - name: Read Gradle versions
        id: get_version
        run: |
          MOD_VERSION=$(grep '^mod_version=' gradle.properties | cut -d'=' -f2)
          MC_VERSION=$(grep '^minecraft_version=' gradle.properties | cut -d'=' -f2)
          VERSION="${MOD_VERSION}+${MC_VERSION}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: docker/Dockerfile
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ steps.repo_name.outputs.repo }}:${{ steps.get_version.outputs.version }}
